INSERT INTO `mr-myreview`.`est_establishment` (`est_id`, `est_name`, `est_cnpj`, `est_description`, `est_stars`, `est_country`, `est_state`, `est_city`, `est_district`, `est_number`) VALUES ('1', 'Restaurante Legal', '123456', 'Restaurante bem interessante', '4', 'Brasil', 'SC', 'São José', 'Forquilhas', '43');
INSERT INTO `mr-myreview`.`est_establishment` (`est_id`, `est_name`, `est_cnpj`, `est_description`, `est_stars`, `est_country`, `est_state`, `est_city`, `est_district`, `est_number`) VALUES ('2', 'Restaurante Meia Boca', '11155544', 'Restaurante mais ou menos', '3', 'Brasil', 'SC', 'São José', 'Forquilhas', '45');
INSERT INTO `mr-myreview`.`est_establishment` (`est_id`, `est_name`, `est_cnpj`, `est_description`, `est_stars`, `est_country`, `est_state`, `est_city`, `est_district`, `est_number`) VALUES ('3', 'Restaurante Fedido', '444555', 'Fedor ', '2', 'Brasil', 'Santa Catarina', 'São José', 'Forquilhas', '44');
INSERT INTO `mr-myreview`.`est_establishment` (`est_id`, `est_name`, `est_cnpj`, `est_description`, `est_stars`, `est_country`, `est_state`, `est_city`, `est_district`, `est_number`) VALUES ('4', 'Restaurante Massa', '234234', 'Italiano', '5', 'Brasil', 'SC', 'São José', 'Forquilhas', '47');
INSERT INTO `mr-myreview`.`est_establishment` (`est_id`, `est_name`, `est_cnpj`, `est_description`, `est_stars`, `est_country`, `est_state`, `est_city`, `est_district`, `est_number`) VALUES ('5', 'Mac Donalds', '47498', 'Fast-food', '4', 'Brasil', 'Santa Catarina', 'São José', 'Forquilhas', '50');
INSERT INTO `mr-myreview`.`est_establishment` (`est_id`, `est_name`, `est_cnpj`, `est_description`, `est_stars`, `est_country`, `est_state`, `est_city`, `est_district`, `est_number`) VALUES ('6', 'Burguer King', '132165', 'Fast-food', '4', 'Brasil', 'Santa Catarina', 'São José', 'Forquilhas', '41');
INSERT INTO `mr-myreview`.`est_establishment` (`est_id`, `est_name`, `est_cnpj`, `est_description`, `est_stars`, `est_country`, `est_state`, `est_city`, `est_district`, `est_number`) VALUES ('7', 'Tops', '13216235', 'Fast-food', '4', 'Jamaica', 'jubar', 'São Joca', 'Mattos', '100');
INSERT INTO `mr-myreview`.`est_establishment` (`est_id`, `est_name`, `est_cnpj`, `est_description`, `est_stars`, `est_country`, `est_state`, `est_city`, `est_district`, `est_number`) VALUES ('8', 'TopaTeen', '216235', 'Fast-food', '5', 'Jamaica', 'macae', 'MP', 'Mapaca', '400');
INSERT INTO `myreview`.`est_establishment` (`est_id`, `est_city`, `est_cnpj`, `est_country`, `est_description`, `est_district`, `est_name`, `est_number`, `est_stars`, `est_state`) VALUES ('9', 'palhoca', '234235', 'Brasil', 'Fast-food', 'brejaru', 'Perkson', '34', '3', 'SC');
INSERT INTO `myreview`.`est_establishment` (`est_id`, `est_city`, `est_cnpj`, `est_country`, `est_description`, `est_district`, `est_name`, `est_number`, `est_stars`, `est_state`) VALUES ('10', 'palhoca', '232235', 'Brasil', 'Fast-food', 'pacheco', 'Rest Life', '34', '3', 'SC');
INSERT INTO `myreview`.`est_establishment` (`est_id`, `est_city`, `est_cnpj`, `est_country`, `est_description`, `est_district`, `est_name`, `est_number`, `est_stars`, `est_state`) VALUES ('11', 'palhoca', '233335', 'Brasil', 'Fast-food', 'brejaru', 'Albertos', '34', '3', 'SC');
INSERT INTO `myreview`.`est_establishment` (`est_id`, `est_city`, `est_cnpj`, `est_country`, `est_description`, `est_district`, `est_name`, `est_number`, `est_stars`, `est_state`) VALUES ('12', 'florianopolis', '234435', 'Brasil', 'Fast-food', 'carianos', 'killes', '34', '3', 'SC');
INSERT INTO `myreview`.`est_establishment` (`est_id`, `est_city`, `est_cnpj`, `est_country`, `est_description`, `est_district`, `est_name`, `est_number`, `est_stars`, `est_state`) VALUES ('13', 'florianopolis', '234535', 'Brasil', 'Fast-food', 'ratones', 'Sakkson', '34', '3', 'SC');

