
INSERT INTO est_establishments(est_id, est_city, est_cnpj, est_country, est_description, est_district, est_name, est_number, est_stars, est_state) values (50, "São José", "90467238999834", "brazil","O melhor", "Kobrasol", "Restaurante Interessante", 39, 4.0, "Santa Catarina");
INSERT INTO est_establishments(est_id, est_city, est_cnpj, est_country, est_description, est_district, est_name, est_number, est_stars, est_state) values (8, "São José", "9046722229832", "brazil","Restaurante Legal", "Kobrasol", "Delicias do Mar", 21, 4.8, "Santa Catarina");
INSERT INTO est_establishments(est_id, est_city, est_cnpj, est_country, est_description, est_district, est_name, est_number, est_stars, est_state) values (9, "São José", "9046723339832", "brazil","Restaurante Elegante", "Kobrasol", "Cops", 22, 4.3, "Santa Catarina");
INSERT INTO est_establishments(est_id, est_city, est_cnpj, est_country, est_description, est_district, est_name, est_number, est_stars, est_state) values (10, "São José", "9046733399832", "brazil","O melhor Lugar", "Kobrasol", "Delicias do Bairro", 24, 2, "Santa Catarina");
INSERT INTO est_establishments(est_id, est_city, est_cnpj, est_country, est_description, est_district, est_name, est_number, est_stars, est_state) values (11, "São José", "9046111999832", "brazil","Comer é aqui", "Kobrasol", "Chutz", 101, 4.9, "Santa Catarina");
INSERT INTO est_establishments(est_id, est_city, est_cnpj, est_country, est_description, est_district, est_name, est_number, est_stars, est_state) values (12, "São José", "9046444999832", "brazil","Recanto do Gordinho", "Kobrasol", "Bingos", 102, 5, "Santa Catarina");
INSERT INTO est_establishments(est_id, est_city, est_cnpj, est_country, est_description, est_district, est_name, est_number, est_stars, est_state) values (13, "São José", "9046555999832", "brazil","Encha a Barriga", "Kobrasol", "Delicias da Casa", 103, 4.3, "Santa Catarina");
INSERT INTO est_establishments(est_id, est_city, est_cnpj, est_country, est_description, est_district, est_name, est_number, est_stars, est_state) values (14, "São José", "9046766699832", "brazil","O melhor de todos", "Kobrasol", "Lopes",109, 4.3, "Santa Catarina");
INSERT INTO est_establishments(est_id, est_city, est_cnpj, est_country, est_description, est_district, est_name, est_number, est_stars, est_state) values (15, "São José", "9046723777832", "brazil","Pura Gula", "Kobrasol", "Delicias De Comer", 110, 2, "Santa Catarina");
INSERT INTO est_establishments(est_id, est_city, est_cnpj, est_country, est_description, est_district, est_name, est_number, est_stars, est_state) values (16, "São José", "9046723888832", "brazil","Restaurante Diferençiado", "Kobrasol", "Vinis", 111, 2, "Santa Catarina");
INSERT INTO est_establishments(est_id, est_city, est_cnpj, est_country, est_description, est_district, est_name, est_number, est_stars, est_state) values (17, "São José", "9046723999832", "brazil","Restaurante Moderno", "Kobrasol", "Delicias", 112, 5, "Santa Catarina");

INSERT INTO est_establishments(est_id, est_city, est_cnpj, est_country, est_description, est_district, est_name, est_number, est_stars, est_state) values (18, "Palhoça", "2226723899832", "brazil","O melhor da Região", "Brejaru", "Delicias da Estação", 113, 5, "Santa Catarina");
INSERT INTO est_establishments(est_id, est_city, est_cnpj, est_country, est_description, est_district, est_name, est_number, est_stars, est_state) values (19, "Palhoça", "3336723899832", "brazil","Restaurante Chique", "Brejaru", "Comer Comer", 114, 5, "Santa Catarina");
INSERT INTO est_establishments(est_id, est_city, est_cnpj, est_country, est_description, est_district, est_name, est_number, est_stars, est_state) values (20, "Palhoça", "4446723899832", "brazil","Restaurante de Luxo", "Brejaru", "Saborear", 115, 4.3, "Santa Catarina");
INSERT INTO est_establishments(est_id, est_city, est_cnpj, est_country, est_description, est_district, est_name, est_number, est_stars, est_state) values (21, "Palhoça", "5556723899832", "brazil","Restaurante Barato", "Pachecos", "Divas", 116, 4.3, "Santa Catarina");
INSERT INTO est_establishments(est_id, est_city, est_cnpj, est_country, est_description, est_district, est_name, est_number, est_stars, est_state) values (22, "Palhoça", "6666723899832", "brazil","O Melhor no Que Faz", "Pachecos", "Gentlemans", 117, 4.8, "Santa Catarina");
INSERT INTO est_establishments(est_id, est_city, est_cnpj, est_country, est_description, est_district, est_name, est_number, est_stars, est_state) values (23, "Palhoça", "7776723899832", "brazil","Delicia é Sobrenome", "Pachecos", "Jellys", 118, 4.8, "Santa Catarina");
INSERT INTO est_establishments(est_id, est_city, est_cnpj, est_country, est_description, est_district, est_name, est_number, est_stars, est_state) values (24, "Palhoça", "88886723999832", "brazil","Pratos e Pratos", "Praia do Sonho", "Tabs", 119, 2, "Santa Catarina");
INSERT INTO est_establishments(est_id, est_city, est_cnpj, est_country, est_description, est_district, est_name, est_number, est_stars, est_state) values (25, "Palhoça", "99999723999832", "brazil","Saboreie", "Praia do Sonho", "Kisses", 120, 4.8, "Santa Catarina");

INSERT INTO est_establishments(est_id, est_city, est_cnpj, est_country, est_description, est_district, est_name, est_number, est_stars, est_state) values (26, "Uruguaiana", "90467389992222", "brazil","Fast-Food", "Centro", "Loves", 121, 1, "Rio Grande do Sul");
INSERT INTO est_establishments(est_id, est_city, est_cnpj, est_country, est_description, est_district, est_name, est_number, est_stars, est_state) values (27, "Uruguaiana", "90467389993333", "brazil","Comá bem", "Centro", "Pallets", 122, 3.2, "Rio Grande do Sul");
INSERT INTO est_establishments(est_id, est_city, est_cnpj, est_country, est_description, est_district, est_name, est_number, est_stars, est_state) values (28, "Uruguaiana", "90467389994444", "brazil","Comá Rápido", "Centro", "Restaurante Nice", 123, 3.2, "Rio Grande do Sul");
INSERT INTO est_establishments(est_id, est_city, est_cnpj, est_country, est_description, est_district, est_name, est_number, est_stars, est_state) values (29, "Caxias do Sul", "90672389995555", "brazil","Santa Fé", "Kobrasol", "Cool", 124, 3.8, "Rio Grande do Sul");
INSERT INTO est_establishments(est_id, est_city, est_cnpj, est_country, est_description, est_district, est_name, est_number, est_stars, est_state) values (30, "Caxias do Sul", "90467389996666", "brazil","Santa Fé", "Kobrasol", "Nices", 125, 3.8, "Rio Grande do Sul");
INSERT INTO est_establishments(est_id, est_city, est_cnpj, est_country, est_description, est_district, est_name, est_number, est_stars, est_state) values (31, "Pelotas", "90467238997777", "brazil","Você que Pede", "Fragata", "Fines", 126, 5, "Rio Grande do Sul");
INSERT INTO est_establishments(est_id, est_city, est_cnpj, est_country, est_description, est_district, est_name, est_number, est_stars, est_state) values (32, "Pelotas", "90467238998888", "brazil","Lugar Divino para Comer", "Gants", "Natura", 127, 2, "Rio Grande do Sul");


INSERT INTO est_establishments(est_id, est_city, est_cnpj, est_country, est_description, est_district, est_name, est_number, est_stars, est_state) values (33, "Porto Alegre", "9346723999822", "brazil","O melhor da Cidade", "Anchieta", "Giants", 130, 2, "Rio Grande do Sul");
INSERT INTO est_establishments(est_id, est_city, est_cnpj, est_country, est_description, est_district, est_name, est_number, est_stars, est_state) values (34, "Porto Alegre", "9446728999842", "brazil","Compa Aqui", "Arquipélago", "Reis", 131, 3, "Rio Grande do Sul");
INSERT INTO est_establishments(est_id, est_city, est_cnpj, est_country, est_description, est_district, est_name, est_number, est_stars, est_state) values (35, "São Paulo", "9546723899852", "brazil","Já Comi", "Barra Funda", "Kingst", 132, 4, "São Paulo");
INSERT INTO est_establishments(est_id, est_city, est_cnpj, est_country, est_description, est_district, est_name, est_number, est_stars, est_state) values (36, "São Paulo", "9646723999862", "brazil","Aqui é Bom", "Barra Funda", "Novers", 133, 5, "São Paulo");
INSERT INTO est_establishments(est_id, est_city, est_cnpj, est_country, est_description, est_district, est_name, est_number, est_stars, est_state) values (38, "Guarulhos", "9746728999872", "brazil","Venha Sempre e Volte Sempre", "Água Azul", "Grand", 134, 5, "São Paulo");

INSERT INTO est_establishments(est_id, est_city, est_cnpj, est_country, est_description, est_district, est_name, est_number, est_stars, est_state) values (39, "Guarulhos", "9846723999832", "brazil","Saia Feliz", "Água Azul", "Yans", 140, 3.8, "São Paulo");
INSERT INTO est_establishments(est_id, est_city, est_cnpj, est_country, est_description, est_district, est_name, est_number, est_stars, est_state) values (40, "Guarulhos", "9946728999832", "brazil","Coma e Corra", "Bananal", "Grit", 141, 3.8, "São Paulo");
INSERT INTO est_establishments(est_id, est_city, est_cnpj, est_country, est_description, est_district, est_name, est_number, est_stars, est_state) values (41, "Campinas", "9106728999832", "brazil","Comer é Aqui", "Guanabara", "Grot", 142, 3.8, "São Paulo");
INSERT INTO est_establishments(est_id, est_city, est_cnpj, est_country, est_description, est_district, est_name, est_number, est_stars, est_state) values (42, "Campinas", "9116738999832", "brazil","Legal é Comer", "Guanabara", "Erai", 143, 5, "São Paulo");
INSERT INTO est_establishments(est_id, est_city, est_cnpj, est_country, est_description, est_district, est_name, est_number, est_stars, est_state) values (43, "Osasco", "9126728999832", "brazil","Se Permita Comer", "Bandeiras", "Gus", 144, 5, "São Paulo");

INSERT INTO est_establishments(est_id, est_city, est_cnpj, est_country, est_description, est_district, est_name, est_number, est_stars, est_state) values (44, "Osasco", "9126723899982", "brazil","O melhor do Kobrasol", "Bandeiras", "Ops", 150, 4.8, "São Paulo");
INSERT INTO est_establishments(est_id, est_city, est_cnpj, est_country, est_description, est_district, est_name, est_number, est_stars, est_state) values (45, "Rio de Janeiro", "9137238999832", "brazil","O melhor do Kobrasol", "Gávea", "Hey Dude", 151, 4.8, "Rio de Janeiro");
INSERT INTO est_establishments(est_id, est_city, est_cnpj, est_country, est_description, est_district, est_name, est_number, est_stars, est_state) values (46, "Rio de Janeiro", "9167238999832", "brazil","O melhor do Kobrasol", "Gávea", "Camarada", 152, 2.7, "Rio de Janeiro");
INSERT INTO est_establishments(est_id, est_city, est_cnpj, est_country, est_description, est_district, est_name, est_number, est_stars, est_state) values (47, "Nova Iguaçu", "9156238999832", "brazil","O melhor do Kobrasol", "Adrianópolis", "Joins", 153, 5, "Rio de Janeiro");
INSERT INTO est_establishments(est_id, est_city, est_cnpj, est_country, est_description, est_district, est_name, est_number, est_stars, est_state) values (80, "Duque de Caxias", "1667238999832", "brazil","O melhor do Kobrasol", "Saracuruna", "Ads", 154, 4, "Rio de Janeiro");
